{% set name = "niworkflows" %}
{% set version = "1.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/niworkflows-{{ version }}.tar.gz
  sha256: 3e810029d439c7735698ff21ad5b5ddda17e21456825965a22494edd8cd1044e

build:
  entry_points:
    - niworkflows-boldref = niworkflows.cli.boldref:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - acres
    - attrs >=20.1
    - jinja2 >=3
    - looseversion
    - matplotlib-base >=3.5
    - nibabel >=3.0
    - nilearn >=0.8
    - nipype >=1.8.5
    - nitransforms >=22.0.0
    - numpy >=1.20
    - packaging
    - pandas >=1.2
    - pybids >=0.15.1
    - pyyaml >=5.4
    - scikit-image >=0.18
    - scipy >=1.8
    - seaborn >=0.11
    - svgutils >=0.3.4
    - templateflow >=23.1
    - transforms3d >=0.4

test:
  imports:
    - niworkflows
  commands:
    - niworkflows-boldref --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/nipreps/niworkflows
  summary: NeuroImaging Workflows provides processing tools for magnetic resonance images of the brain.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Dhananjhay
